@LoudApi_HostAddress = http://localhost:5152

GET {{LoudApi_HostAddress}}/priorities
Accept: application/json

###

GET {{LoudApi_HostAddress}}/priorities/1
Accept: application/json

###

POST {{LoudApi_HostAddress}}/priorities
Content-Type: application/json

{
  "title": "Study HTTP status codes",
  "description": "Understand 200, 201, 400, 404 and 500."
}

###

PUT {{LoudApi_HostAddress}}/priorities/1
Content-Type: application/json

{
  "title": "Study HTTP status codes",
  "description": "Understand 200, 201, 400, 404 and 500.",
  "isDone": true
}

###

DELETE {{LoudApi_HostAddress}}/priorities/1
